<?php
Route::get('/','AdminController@index')->name('admin');
Route::get('/login','AdminController@login')->name('login');
Route::post('/verify/trusted/browser','AdminController@verifyTrustedBrowser');
Route::post('/post/verify/trusted/browser','AdminController@postVerifyTrustedBrowser');
Route::get('/browser/detect','AdminController@browserDetect')->name('browser-detect');
Route::get('/register','AdminController@register')->name('register');
Route::get('/forget','AdminController@forget')->name('forget');
Route::post('/forget','AdminController@postForget')->name('post-forget');
Route::get('/reset','AdminController@reset')->name('reset');
Route::post('/reset','AdminController@postReset')->name('post-reset');
Route::get('/activate','AdminController@activate')->name('get-activate');
Route::post('/login','AuthController@login')->name('post-login');
Route::post('/logout','AuthController@logout')->name('post-logout');
Route::post('/logout/lock','AuthController@logoutLock')->name('post-logout-lock');
Route::post('/lock','AuthController@lock')->name('post-lock');
Route::post('/unlock','AuthController@unlock')->name('post-unlock');
Route::get('/blocked','AuthController@blocked')->name('blocked');
