<?php
Route::get('/','UserController@index')->name('user');
Route::post('/login','UserAuthenticationController@login')->name('post-login');
Route::post('/register','UserAuthenticationController@register')->name('post-register');
Route::post('/verify/otp','UserAuthenticationController@verifyOtp')->name('post-verify-otp');
Route::post('/reset/password/otp','UserAuthenticationController@verifyUserOtp')->name('post-verify-user-otp');
Route::post('reset/password/string','UserAuthenticationController@resetPasswordString')->name('post-reset-user-password');
Route::post('add/location','HomeController@addLocation')->name('add-location');
Route::post('get/info','HomeController@getInfo')->name('getinfo');
Route::post('save/info','HomeController@saveInfo')->name('saveInfo');
Route::post('location/update','HomeController@locationUpdate')->name('update-location');
Route::post('update/dp','HomeController@updateDp')->name('update-dp');
Route::post('coupon/list','HomeController@couponList')->name('coupon-list');
Route::post('get/saved/locations','HomeController@savedLocations')->name('get-saved-locations');
Route::post('check/coupon','HomeController@checkCoupon')->name('check-coupon');
Route::post('update/device/token','HomeController@updateDeviceToken')->name('update-token');
Route::post('post/ride','HomeController@postRide')->name('post-ride');
Route::post('rider/accepted/check','HomeController@riderAccepted')->name('rider-accepted');
Route::post('view/rider','HomeController@viewRider')->name('view-rider');